default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

remote: &remote
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { '' } %>

development:
  <<: *default
  database: nexum_dev

test:
  <<: *default
  database: nexum_test

production:
  <<: *remote
